### ISSUE TITLE
Have Writers and Readers switch to Backups

### ISSUE THREAD

**Issue by gslightmage** [Tusamarco/proxy_sql_tools#14]
Is it possible via weighting to have 1 Reader and 1 Writer. Then with 8050 and 8052 with extra systems listed, Then the proxy script would auto switch over when the primary Reader & writer fail?

50: 1 Server listed
52: 1 server listed (possibly same server as in 50)
8050: servers 1-3 
8052: servers 1-3

**Comment by Tusamarco** [comment]
Hi @gslightmage, yes it is possible to implement it.
 Is this something that you need as urgent request because a stopper or can it be schedule in a longer time frame?
I am in the process of adding additional features as failback #12, so I can work on this as well at the same time.
But if urgent I can give it higher priority.

**Comment by gslightmage** [comment]
If it's not too much trouble, I would appreciate it sooner than later. Without it, I may have to abandon using it. :(
