### ISSUE TITLE
Critical: If galera_check.pl can't connect to the admin interface, it doesn't remove the .pid file.

### ISSUE THREAD

**Issue by ethaniel** [Tusamarco/proxy_sql_tools#6]
I am setting up the galera_check.pl on my system and I've noticed this error:

```
DBI connect('host=10.0.0.1;port=3310','admin',...) failed: Can't connect to MySQL server on '10.0.0.1' (111) at /usr/bin/proxysql_galera_check.pl line 1488
Can't call method "prepare" on an undefined value at /usr/bin/proxysql_galera_check.pl line 1036.
```

(i didn't provide a correct port and it failed).

What I've noticed is that the /tmp/proxysql_galera_check_500_W_501_R.pid is still there after the script has exited.

And when I start the script again, I have this in my error log:

```
[ERROR] Another process is running using the same HostGroup and settings,
 Or orphan pid file. check in /tmp/proxysql_galera_check_500_W_501_R.pid
```

**Comment by Tusamarco** [comment]
Yes that is by design to prevent multiple check to run one on top of the
other on the same hostgroup, also port must be define.
keep in mind the script was create for demo purpose, so I am happy to
include whatever fix it may make it more robust.


------------------------------------------------
Marco Tusa, 
Mobile: +1-613-282-7337
do something for your planet!
http://www.tusacentral.net/
------------------------------------------------
Save a tree... please don't print this e-mail unless you really need to

**Comment by ethaniel** [comment]
If the script fails once, then the whole monitoring is cancelled because the script doesn't delete it's .pid file on exit.

Unfortunately, I am not that fluid in perl to provide a fix.

**Comment by Tusamarco** [comment]
Yes correct and I agree not good... what you suggest .. not by code but as logic ... 
something do the check fail once then if try again check the ps and if nothing is running remove the lock and run?

**Comment by Tusamarco** [comment]
Just be clear not the whole monitor but only the scheduled monitor for that HostGroup. The check work against one pair of hostgroup. So this is logically correct, as you cannot have more than one proxy on ip:port or mysql on ip:port you cannot have more than one check running on that specific HG.
Inside the file there is the pid what I can do is to check when starting if the PID is still active and if so  fail the execution if not remove the lock. 
Sound reasonable ?

**Comment by Tusamarco** [comment]
fixed will post it soon and it will act as described above
